# Generated by Django 4.1.6 on 2023-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_securityquestion_profile_security_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_question',
            field=models.CharField(choices=[('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In what city were you born?'), ('mother_maiden', "What is your mother's maiden name?"), ('first_school', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?')], default='', max_length=100),
        ),
    ]
