# Generated by Django 4.1.7 on 2023-04-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
